# Generated by Django 4.0 on 2021-12-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('D', 'Done'), ('F', 'Failed'), ('O', 'Ongoing')], max_length=1)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
        migrations.CreateModel(
            name='LongTerm',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.work')),
                ('end_date', models.DateField()),
            ],
            bases=('schedule.work',),
        ),
        migrations.CreateModel(
            name='ShortTerm',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.work')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            bases=('schedule.work',),
        ),
    ]
