# Generated by Django 4.0 on 2021-12-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='uid',
            new_name='user',
        ),
    ]
