# Generated by Django 4.0 on 2021-12-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_repeat_shortterm_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortterm',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shortterm',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
