# Generated by Django 4.0 on 2021-12-13 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_shortterm_end_time_alter_shortterm_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeat',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='repeat',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repeat',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
