# Generated by Django 4.0 on 2021-12-14 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_uid'),
        ('schedule', '0004_repeat_end_time_repeat_start_date_repeat_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.users'),
            preserve_default=False,
        ),
    ]
