# Generated by Django 4.0 on 2021-12-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_repeated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repeated',
        ),
    ]
