# Generated by Django 4.0 on 2021-12-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_delete_repeated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('D', 'Done'), ('F', 'Failed'), ('O', 'Ongoing')], max_length=1),
        ),
    ]
